//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Host.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/LauncherLib")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Ping", ReplyAction="http://tempuri.org/IService1/PingResponse")]
        string Ping();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Ping", ReplyAction="http://tempuri.org/IService1/PingResponse")]
        System.Threading.Tasks.Task<string> PingAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetMachineName", ReplyAction="http://tempuri.org/IService1/GetMachineNameResponse")]
        string GetMachineName();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetMachineName", ReplyAction="http://tempuri.org/IService1/GetMachineNameResponse")]
        System.Threading.Tasks.Task<string> GetMachineNameAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SendZippedDirectory", ReplyAction="http://tempuri.org/IService1/SendZippedDirectoryResponse")]
        void SendZippedDirectory(System.IO.Stream zipFileStream);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SendZippedDirectory", ReplyAction="http://tempuri.org/IService1/SendZippedDirectoryResponse")]
        System.Threading.Tasks.Task SendZippedDirectoryAsync(System.IO.Stream zipFileStream);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/StartProcessFromZipDir", ReplyAction="http://tempuri.org/IService1/StartProcessFromZipDirResponse")]
        void StartProcessFromZipDir(string path, string arguments);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/StartProcessFromZipDir", ReplyAction="http://tempuri.org/IService1/StartProcessFromZipDirResponse")]
        System.Threading.Tasks.Task StartProcessFromZipDirAsync(string path, string arguments);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/KillProcessFromZipDir", ReplyAction="http://tempuri.org/IService1/KillProcessFromZipDirResponse")]
        void KillProcessFromZipDir();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/KillProcessFromZipDir", ReplyAction="http://tempuri.org/IService1/KillProcessFromZipDirResponse")]
        System.Threading.Tasks.Task KillProcessFromZipDirAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        Host.ServiceReference1.CompositeType GetDataUsingDataContract(Host.ServiceReference1.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<Host.ServiceReference1.CompositeType> GetDataUsingDataContractAsync(Host.ServiceReference1.CompositeType composite);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Host.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Host.ServiceReference1.IService1>, Host.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public string Ping() {
            return base.Channel.Ping();
        }
        
        public System.Threading.Tasks.Task<string> PingAsync() {
            return base.Channel.PingAsync();
        }
        
        public string GetMachineName() {
            return base.Channel.GetMachineName();
        }
        
        public System.Threading.Tasks.Task<string> GetMachineNameAsync() {
            return base.Channel.GetMachineNameAsync();
        }
        
        public void SendZippedDirectory(System.IO.Stream zipFileStream) {
            base.Channel.SendZippedDirectory(zipFileStream);
        }
        
        public System.Threading.Tasks.Task SendZippedDirectoryAsync(System.IO.Stream zipFileStream) {
            return base.Channel.SendZippedDirectoryAsync(zipFileStream);
        }
        
        public void StartProcessFromZipDir(string path, string arguments) {
            base.Channel.StartProcessFromZipDir(path, arguments);
        }
        
        public System.Threading.Tasks.Task StartProcessFromZipDirAsync(string path, string arguments) {
            return base.Channel.StartProcessFromZipDirAsync(path, arguments);
        }
        
        public void KillProcessFromZipDir() {
            base.Channel.KillProcessFromZipDir();
        }
        
        public System.Threading.Tasks.Task KillProcessFromZipDirAsync() {
            return base.Channel.KillProcessFromZipDirAsync();
        }
        
        public Host.ServiceReference1.CompositeType GetDataUsingDataContract(Host.ServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<Host.ServiceReference1.CompositeType> GetDataUsingDataContractAsync(Host.ServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
    }
}
